### ISSUE TITLE
admini and select2

### ISSUE THREAD

**Issue by noxtras** [lekoala/admini#1]
Hello,
I can't seem to be able to get Select2 to work properly (when clicked, it doesn't open the ... select and search div). If I don't load admini.min.css, it works. 
Do you know what it could be?

**Comment by lekoala** [comment]
I don't see why it would be a problem

I made a demo here https://admini.vercel.app/select2.html and it all looks ok. Could have a look and see if you do anything different?
otherwise a demo showing the issue would be helpful

**Comment by noxtras** [comment]
Thanks for the message:) I don't have the mindset to debug the select2 issue.. maybe it was because of a modal? Anyway, I switched to tomselect, seems faster. Thank you again.
